Depend on faraday 0.8.X as 0.9.0 breaks compatibility
0.9.0 seems to have changed how open_timeout is handled, so running the
test suite with 0.9.0 raises the following error:

NoMethodError: undefined method `open_timeout=' for
<Faraday::ConnectionOptions:0x007ff0220da470>